import { IProduct } from '../app/types';


export const PRODUCTS_MOCK_DATA: IProduct[] = [
    {
        id: 1,
        title: 'Качели',
        image: "https://vse-v-sport.ru/image/cache/catalog/dachniy-otdish/absolut/kacheli-2-mesta-500x500.png",
        price: 10000,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 2,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 0,
        isFavourite: true,
    },
    {
        id: 3,
        title: 'Качели',
        image: "https://interier-foto.ru/wp-content/uploads/dlinnye-foto-4.jpg",
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 4,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 0,
        isFavourite: false,
    },
    {
        id: 5,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: true,
    },
    {
        id: 6,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 7,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 0,
        isFavourite: false,
    },
    {
        id: 8,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 9,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 10,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 11,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 12,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 13,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 14,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 15,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 16,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 17,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 18,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 19,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
    {
        id: 20,
        title: 'Качели',
        image: null,
        price: 22222,
        discount: 10,
        isFavourite: false,
    },
]